on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4

      - name: Install kiwi
        run: |
          export DEBIAN_FRONTEND=noninteractive
          curl https://download.opensuse.org/repositories/Virtualization:/Appliances:/Builder/xUbuntu_24.04/Release.key \
            | sudo gpg --dearmor -o /etc/apt/keyrings/kiwi.gpg
          echo 'deb [signed-by=/etc/apt/keyrings/kiwi.gpg] https://download.opensuse.org/repositories/Virtualization:/Appliances:/Builder/xUbuntu_24.04/ ./' \
            | sudo tee /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install -y python3-kiwi dnf
          kiwi --version

      # Should be able to remove this when runns support Ubuntu 25.04+,
      # as the distribution-gpg-keys package is available there.
      - name: Setup Fedora keys
        run: |
          git clone --depth 1 https://github.com/rpm-software-management/distribution-gpg-keys
          sudo mkdir /usr/share/distribution-gpg-keys/
          sudo cp -R distribution-gpg-keys/keys/fedora /usr/share/distribution-gpg-keys/

      - name: Build image
        run: |
          sudo ./kiwi-build \
            --kiwi-file=Fedora-Mobility.kiwi \
            --image-type=oem \
            --image-profile=SDM845-Disk \
            --output-dir ./outdir

      - name: Upload image build log
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: image-root.log
          path: ./outdir-build/build/image-root.log

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Fedora-Mobility.aarch64-Rawhide.raw
          path: ./outdir-build/Fedora-Mobility.aarch64-Rawhide.raw
